### ISSUE TITLE
Code for uniformity feature distribution

### ISSUE THREAD

**Issue by zhangdan8962** [SsnL/align_uniform#3]
Hi,

I am wondering if you can provide the code for generating uniformity feature distribution plot in Fig 3 in your paper?

Thank you in advance for the help!

**Comment by ssnl** [comment]
I'm sorry that I can't directly provide the code. But it is rather straightforward. Top is isotropic 2d Gaussian KDE, plotted with `plt.imshow`; bottom is vMF KDE, likely plotted with `sns.histplot`.

**Comment by zhangdan8962** [comment]
Thank you so much!
So for this experiment, did you train a Alexnet backbone followed by MLP? If so, what does architecture of such MLP look like?

**Comment by ssnl** [comment]
The architecture is the same AlexNet encoder in this repo. As described in paper sec 4, the visualization is simply on S^1 output of that encoder. MLP head that people say is just a fancy name for deeper encoder and using intermediate features.

**Comment by zhangdan8962** [comment]
I am sorry but I am still kind of confused. The original structure of AlexNet after maxpooling palyer is 2048-2048-1000 for ImageNet. Are you saying you used 2048-2048-2 for this experiment?

**Comment by ssnl** [comment]
I believe it is just the encoder in this repo’s STL-10 example with a
feature dimension of 2.

**Comment by zhangdan8962** [comment]
Got it!

Really appreciate the help!
