### ISSUE TITLE
Why unit hypersphere benefits representation learning ?

### ISSUE THREAD

**Issue by demdecuong** [SsnL/align_uniform#5]
Hi sir, thank you for your amazing work and I am new to representation learning. 
I have read the paper "Understanding Contrastive Representation Learning through Alignment and Uniformity on the Hypersphere" but my knowledge is not enough to understand all things. 

1. what is the relation between uniform loss and unit hypersphere since the gaussian sample does point into normal distribution then I misunderstand the relationship.
2. Why hypersphere is good in representation learning?
3. Why we need both alignment and uniformity, why not alignment only due to we want to measure the distance among points in a common space.

Once again, your paper is very inspiring. Thank you so much.

**Comment by ssnl** [comment]
Hi @demdecuong , I'm not sure if I understand your questions so feel free to correct me if I am not answering them correctly.
1. As discussed in Sec. 4.1.2, on the unit hypersphere, points/distributions minimizing the average Gaussian potential (the uniformity loss) converges to / is uniform. There is not really any sample from a Gaussian distribution here.
2. Please see Sec. 6 for discussion on this.
3. Only having alignment is easily satisfied by the degenerate solution of mapping all samples to the sample feature. As argued in paper, uniformity preserves information and avoids degeneracy.

**Comment by demdecuong** [comment]
Thank you for your answering.
