### ISSUE TITLE
How can I get 2D features like Fig.3?

### ISSUE THREAD

**Issue by HaoranTang** [SsnL/align_uniform#6]
Hi Tongzhou,

I am really interested to analyze feature uniformity like you did in Figure 3. I am a bit confused about how to get L2-normalized features on a 2D unit circle (S^1) before applying KDE, suppose my features.size is ([512, 512]). Looking forward to hearing from you, thanks!!

**Comment by ssnl** [comment]
Hi! You need to modify the network to output to S1. It is not for general dimensions as it is hard to visualize uniformity of features in high dimensions.

**Comment by HaoranTang** [comment]
Hi, thank you for the clarification! Really interesting and motivating paper by the way!

**Comment by ssnl** [comment]
Glad that you liked it! Feel free to reach out if you have further questions.
