### ISSUE TITLE
Proof should be corrected

### ISSUE THREAD

**Issue by juhosattila** [SsnL/align_uniform#7]
Hi! I'd like to have a quick remark for the proof of Theorem 1, specifically to the analysis of the convergence rate.

You define the following:

$$
Y_i := e^{\frac{1}{\tau}\langle f(X_i^-), f(X) \rangle} - \mathbb{E}_{\tilde{X}} [ e^{\frac{1}{\tau}\langle f(\tilde{X}), f(X) \rangle} ].
$$

First, you rely on the fact that $Y_i$'s are independent, which I didn't fully refute, but seems highly unlikely. Observe how all the $Y_i$'s depend on the same X. Without having the second mean-term, the truncated $Y_i$'s could be chosen such that they become dependent.

Second, during the derivation that utilises the Berry-Esseen theorem, in the second line you rewrite the mean into the integral of probabilities, which are not densities. I did not fully understand this transformation and I am also skeptical about it. Integrating pure probability values, again not a density function, is strange.

In my humble opinion, both of these question marks could be tackled by rewriting the proof the following way.

i) First, it is easy to prove that

$$
\mathbb{E}(Y_i) = 0,
$$

$$
\mathbb{E}(Y_i | X=x) = 0, \text{ for any } x\in\mathbb{R}
$$

ii) Also, notice that the $Y_i$'s are in fact conditionally independent with respect to the condition $X=x$, for any $x \in \mathbb{R}$.

iii) And, then, apply the following derivation:

$$
\mathbb{E}\bigg|\frac{1}{M}\sum_i Y_i\bigg| = \frac{1}{M}\mathbb{E}\bigg|\sum_i Y_i\bigg|
\leq \frac{1}{M}\sqrt{\mathbb{E}\bigg(\sum_i Y_i\bigg)^2}.
$$

Using the law of total expected value:

$$
\mathbb{E}\bigg(\sum_i Y_i\bigg)^2 = \int \underbrace{\mathbb{E}\bigg[\bigg(\sum_i Y_i\bigg)^2 \bigg| X=x\bigg]}_\text{conditional variance} d\mu_X(x).
$$

Now the mid term is the conditional variance of the conditionally independent variables $Y_i$ with conditional mean $\mathbb{E}(Y_i|X=x)=0.$ So it splits up into the sum of conditional variances:

$$
\mathbb{E}\bigg(\sum_i Y_i\bigg)^2 = \int \sum_i\mathbb{E}\bigg[Y_i^2 \Big| X=x\bigg] d\mu_X(x) 
$$

Reapply the law of total expected value for all $i$'s:

$$
\ldots = \sum_i \mathbb{E}(Y_i^2)=M\sigma^2_Y.
$$

Finally,

$$
\mathbb{E}\bigg|\frac{1}{M}\sum_i Y_i\bigg| = \frac{1}{M}\sqrt{M\sigma^2_Y} = \frac{\sigma_Y}{\sqrt{M}} = \mathcal{O}(M^{-1/2}). 
$$

Observe, how we avoided using the fancy theorem of Berry-Esseen. :)

**Comment by ssnl** [comment]
Hi @juhosattila , Thanks for your note! I will take a detailed look at your derivation later and respond to that part in another reply.

I want to first respond to your two remarks on my proof:
1.  $Y_i$'s are iid **conditioned on $X$**, which is what I actually use in the proof. However, I agree that it is not made clear in text. 
2. The rewriting of expectation into integral of CDFs (probabilities) is a known formula (e.g., see [here](https://ckrao.wordpress.com/2012/07/18/the-mean-of-a-random-variable-in-terms-of-its-cdf/), which can be simplified for non-negative RVs, which is what I used).


Thanks for pointing both out. I will update the manual script to be clearer on both points.

**Comment by juhosattila** [comment]
Thanks for the quick reply and looking forward to your opinion.

In the mean time, indeed, the connection between the mean and cdf is new to me and very interesting. Honestly, at first glance, it felt odd to integrate normal probability values from a physical perspective. But of course, neither probability densities nor the cfd have any physical unit.

**Comment by ssnl** [comment]
@juhosattila [This](https://math.stackexchange.com/a/64227) describes a good intuition behind the formula.

**Comment by ssnl** [comment]
Hi @juhosattila , thanks for the alternative proof! I like that it is simple and uses more straightforward elementary identities. I  am going to stick with the original proof in the paper, since it is not wrong. However, I will update the paper to be clearer on the points you raised!
