### ISSUE TITLE
Question about normalization

### ISSUE THREAD

**Issue by jasperhyp** [SsnL/align_uniform#8]
Hi Tongzhou, Thanks for continuing to update the work!  I noticed that there is a normalization layer at the end in STL10's Alexnet, whereas in the MoCo version, the ResNet from torchvision does not have such a normalization layer.  This seems to imply that in the MoCo case, the output embeddings used for downstream tasks are not necessarily on the unit hypersphere (as when calculating the loss or being evaluated).  I might be missing something but would this affect the correspondence between the two metrics and the downstream performance?

**Comment by ssnl** [comment]
MoCo has normalization: https://github.com/facebookresearch/moco/blob/78b69cafae80bc74cd1a89ac3fb365dc20d157d3/moco/builder.py#L125-L136

**Comment by jasperhyp** [comment]
Thanks for the prompt response, and yes, but it looks like in the downstream that normalization isn't used as shown here: https://github.com/facebookresearch/moco/blob/78b69cafae80bc74cd1a89ac3fb365dc20d157d3/main_lincls.py#L165.  Or did I miss something?

**Comment by ssnl** [comment]
Yeah, it is not special to moco. In many contrastive learning works, intermediate features are used for downstream transfer. For our results that show correspondence between align&uniform metrics and downstream performances, we used both outputs and intermediate features. The trend is the empirically same in both cases.

**Comment by jasperhyp** [comment]
Thanks for the clarification.  Yes, I did notice that the outputs and fc7 activations of STL-10 encoders both show good correspondence.  This along with the experiment that training on the unit hypersphere improves the performance for downstream tasks using unnormalized intermediate features (as SimCLR shows) is quite interesting. I also agree that most recent CL works are using unnormalized intermediate features for downstream tasks because there are observations that intermediate features just perform better than output downstream. Not sure if there're any empirical results on comparing normalized vs unnormalized features though.

**Comment by ssnl** [comment]
Yeah, picking which layers to use is usually empirically determined. From my observation, usually a few layers before the final normalized output is a good choice!
